config/routes.rb
Rails.application.routes.draw do
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :posts, only: [:create, :destroy]
 # resources :likes, only: [:create]
  post '/like', to: 'likes#create'
  delete '/unlike', to: "likes#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	validates :body, length: {maximum: 255}
	validates :user_id, presence: true
	belongs_to :user
	has_one_attached :image
	has_many :likes

	default_scope -> {order "created_at DESC"}
	

	def liked?(user_id)
		likes.where(user_id: user_id).count > 0
	end
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	has_secure_password
	has_one_attached :avatar
	has_many :posts
	has_many :likes
	
	validates :username, presence: true, length: {maximum: 30 }, uniqueness: {case_sensative: false}
	validates :email, presence: true, uniqueness: {case_sensative: false}
 	validates :password, length: {minimum: 6, maximum: 30}
	validates_email_format_of :email, message: 'The e-mail format is not correct!'
	validates :username, :password, format: { with: /\A[0-9a-zA-Z_.\-]+\Z/, message: "Only alphanumeric characters, and -_."}

	before_save { self.email = email.downcase }
	before_save { self.username = username.downcase }

	def User.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  	end

	def User.new_token
    	SecureRandom.urlsafe_base64
  	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end
	
	def authenticated?(remember_token)
    	BCrypt::Password.new(remember_digest).is_password?(remember_token)
  	end
  	def forget
    	update_attribute(:remember_digest, nil)
 	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
		@post_id = params[:like][:post_id]
		like = Like.create(user_id: current_user.id, post_id: @post_id)
		@count = Post.find(@post_id).likes.count
		respond_to do |format|
			format.js {}
		end
	end

	def destroy
		@post_id = params[:like][:post_id]
		Like.where(post_id: @post_id, user_id: current_user.id).first.destroy!
		@count = Post.find(@post_id).likes.count
		respond_to do |format|
			format.js{}
		end 
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	if signed_in?
		  @feed = current_user.posts
    	@post = Post.new
	end
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	
	before_action :check, only: :destroy

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to root_path
		else
			render "pages#new"
		end
	end

	def destroy

		Post.find(params[:id]).destroy!
		redirect_to root_path
	end

	private
	def post_params
		params.require(:post).permit(:body, :image)
	end

	def check
		unless current_user && Post.find(params[:id]).user_id == current_user.id
			flash[:danger] = "Not your post!"
			redirect_to root_path
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		login = params[:session][:login]
		if login.include? "@"
			user = User.find_by_email(login)  
		else
			user = User.find_by_username(login)
		end

		if user && user.authenticate(params[:session][:password])
			sign_in user
			remember user
			redirect_to user
		else
			flash[:error] = "Invalid username or password"
			render "new"
		end

	end

	def destroy
		sign_out
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      flash[:success] = "Welcome to the Instagram!"
      sign_in @user
  		redirect_to @user		
  	else
  		render :new
  	end
  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'    
    end
  end

  def destroy
      sing_out
      redirect_to root_path
  end

  
  private
   	def user_params
   		params.require(:user).permit(:username, :email, :password, :avatar)
   	end

    def logged_in_user
      unless signed_in?
        flash[:danger] = "Please log in."
        redirect_to '/login'
      end
    end
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
	def pretty_title(title)
		 title.nil? ? "Instagram" : "Instagram | " + title
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def sign_in (user)	
		session[:user_id] = user.id
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		elsif cookies.signed[:user_id]
			user = User.find_by(id: cookies.signed[:user_id])
			if user && user.authenticated?(cookies[:remember_token])
    			sign_in user
   				@current_user = user
  			end
		end
	end
	def current_user?(user_id)
    	user_id == current_user.id if current_user
 	end
	def sign_out
		forget current_user
		session[:user_id] = nil
		@current_user = nil
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token		
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end
	

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= pretty_title(@title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/header" %>
    <div class = "container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "partials/footer"%>
    </div>
  </body>
</html>

app/views/likes/_like.html.erb
<%= form_for(:like, url: unlike_path, method: :delete, remote: true) do |f|%>
	<%= f.hidden_field :post_id, value: post_id %>
	<button type="submit">
		<i class="fa fa-heart"></i>
	</button>
	<%= count %>
<%end%>

app/views/likes/_likes.html.erb
 <div id="like-<%= post.id %>">
	<% @count = post.likes.count%>
	<% if post.liked?(current_user.id) %>
		<%= render "likes/like", post_id: post.id, count: @count%>
	<% else %>
		
		<%= render "likes/unlike", post_id: post.id, count: @count%>
	<% end %>
</div>

app/views/likes/_unlike.html.erb
<%= form_for(:like, url: like_path, remote: true) do |f|%>
	<%= f.hidden_field :post_id, value: post_id %>
	<button type="submit">
		<i class="fa fa-heart-o"></i>
	</button>
	
	<%= count %>
<%end%>

app/views/likes/create.js.erb
$("#like-<%= @post_id %>").html("<%= escape_javascript(render('likes/like', post_id: @post_id, count: @count))%>");

app/views/likes/destroy.js.erb
$("#like-<%= @post_id %>").html("<%= escape_javascript(render('likes/unlike', post_id: @post_id, count: @count))%>");

app/views/pages/about.html.erb
<% @title = "About"%>
<h1>About</h1>

app/views/pages/contact.html.erb
<% @title = "Contact"%>
<h1>Contact</h1>

app/views/pages/index.html.erb
<% @title = "Homepage"%>

<% if signed_in? %>
	<div class="row">
		<div class="col-md-3">
			<% if current_user.avatar.attachment %>
				<%= image_tag current_user.avatar, height: 50 %>
			<% end %>
			<h3> <%= current_user.username %>
				</h3>

				<%= form_for @post do |f| %>
					<div class="form-group">
						<%= f.text_area :body, class: "form-control" %>
					</div>
					<div class="form-group">
						<%= f.file_field :image, class: "form-control" %>
					</div>
					<%= f.submit :submit, class: "btn btn-outline-success" %>
				<% end %>
		</div>
		<div class="col-md-5">
			<%= render @feed %>
		</div>
	</div>
<% else %>
	<div class="jumbotron">
		<h1>Welcome to Instagram!</h1>
	</div>
<% end %>

app/views/partials/_footer.html.erb
<footer class = "footer">
	<small>
		<p>Instagram made by Izat</p>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", '/about'%></li>
			<li><%= link_to "Contact",   '/contact' %></li>
		</ul>
	</nav>
</footer>

app/views/partials/_header.html.erb
<header class = "navbar navbar-fixed-top navbar-inverse">
  <div class = "container">
    <%= link_to "Instagram", root_path , id: "logo"%>
    <nav>
      <ul class = "nav navbar-nav navbar-right">
        <li><%= link_to "Home",  root_path %></li>
        <% if signed_in?%>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Logout", logout_path, method: :delete%></li>
          <li><%= link_to "Edit", edit_user_path(current_user) %></li>
        <% else %>
          <li><%= link_to "Login", login_path%></li>
          <li><%= link_to "Sign up", '/signup'%></li>
        <%end%>
      </ul>
    </nav>
  </div>
</header>

app/views/posts/_post.html.erb
<div class="well">
	<% if post.image.attachment %>
		<figure>
		<%= image_tag post.image, class: "img-fluid img-thumbnail" %>
	</figure>
	<% end %>
	<p><%= post.body %></p> 
	<%= link_to "Delete", post, id: "del", method: :delete, data: {confirm: "U sure?"} if current_user?(post.user_id)%>
	
	<%= render "likes/likes", post: post %>

</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>	
	<div id="error_explanation">
	   	 	<div class="alert alert-danger">
	      		The form contains <%= pluralize(@user.errors.count, "error") %>.
	    	</div>
		<ul>
			<% @user.errors.full_messages.each do |m|%>
				<li><%= m %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>
<div class = "row">
	<div class="col-md-6 col-md-offset-3 ">
		<%= form_for @user do |f|%>
			<%= render 'shared/error_messages' %>
			<%= f.label :username%>
			<%= f.text_field :username, placeholder: "username",class: 'form-control' %>
			<%= f.label :email%>
			<%= f.text_field :email, placeholder: "email",class: 'form-control' %>
			<%= f.label :password%>
			<%= f.password_field :password, placeholder: "password", class: 'form-control' %>
			<div class="overflow">
				<% unless @user.avatar.attachment.nil? %>
				 	<%= image_tag @user.avatar, class: "img-fluid"%>
				<% else %>
					<img class="img-fluid", src="https://www.bsn.eu/wp-content/uploads/2016/12/user-icon-image-placeholder-300-grey.jpg">
			  	<% end %>
		  	</div>
		  	<%= f.file_field :avatar%>
		  	<%= f.submit "Save changes", class: "btn btn-primary"%>
		<% end %>
	</div>
	
</div>

app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <% unless user.avatar.attachment.nil? %>
		    <%= image_tag user.avatar,size: 50%>
	     <% else %>
		     <%=image_tag src="https://www.bsn.eu/wp-content/uploads/2016/12/user-icon-image-placeholder-300-grey.jpg",size: 50%>
  	  <% end %>
      <%= link_to user.username, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class = "row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for @user do |f|%>
			<%= render 'shared/error_messages' %>
			<%= f.label :username%>
			<%= f.text_field :username, placeholder: "username",class: 'form-control' %>
			<%= f.label :email%>
			<%= f.text_field :email, placeholder: "email",class: 'form-control' %>
			<%= f.label :password%>
			<%= f.password_field :password, placeholder: "password", class: 'form-control' %>
			<%= f.file_field :avatar %>
			<%= f.submit :submit, class: "btn btn-primary"%>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3>
        <div class="overflow">
      	<% unless @user.avatar.attachment.nil? %>
			     <%= image_tag @user.avatar, class: "img-fluid"%>
	     	<% else %>
			     <img class ="img-fluid", src="https://www.bsn.eu/wp-content/uploads/2016/12/user-icon-image-placeholder-300-grey.jpg">
		    <% end %>
        	<%= @user.username %>
		      <%= @user.email %>
      </div>
      </h3>
    </section>
  </aside>
  <div class="col-md-9">
     <%= render @user.posts %>
  </div>
</div>